spring.application.name=purchase-service
# server.address=192.168.1.157
# =============================
# Datasource Configuration
# =============================
spring.datasource.url=jdbc:postgresql://localhost:5432/order-service
spring.datasource.username=postgres
spring.datasource.password=sspl

# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
server.servlet.context-path=/masterservice/api

# ===============================================
# Eureka Server Configuration 
# ===============================================
# eureka.client.serviceUrl.defaultZone=http://192.168.1.90:8761/eureka
